[package]
name = "renamite-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "renamite desktop runner"

[[bin]]
name = "renamite"
path = "src/main.rs"

[dependencies]
repose-platform.workspace = true
repose-core.workspace = true
renamite-ui.workspace = true
anyhow.workspace = true
env_logger = "0.11"