[package]
name = "renamite-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "renamite multiplatform editor runner"
default-run = "renamite-desktop"

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "renamite-desktop"
path = "src/main.rs"

[package.metadata.android]
package = "org.mlm.renamite"
apk_name = "renamite"
build_targets = ["aarch64-linux-android"]
split_per_abi = true
resources = "../../others/packaging/res"

[package.metadata.android.application]
label = "Renamite"
fullscreen = false
icon = "@drawable/ic_launcher_monochrome"

[package.metadata.android.sdk]
min_sdk_version = 26
target_sdk_version = 37

[[package.metadata.android.application.activity]]
name = "rust.rlobkit.RlobKitMainActivity"
exported = true
launch_mode = "singleTask"

[[package.metadata.android.application.activity.intent_filter]]
actions = ["android.intent.action.MAIN"]
categories = ["android.intent.category.LAUNCHER"]

[dependencies]
repose-platform.workspace = true
repose-core.workspace = true
renamite-ui.workspace = true
anyhow.workspace = true
env_logger = "0.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15"
log = "0.4"
winit = "0.30"
rlobkit-app-events = { version = "0.5", features = ["jni-bridge"] }
