name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: mlm-games/ci/.github/workflows/rust-app-ci.yml@v1
    with:
      app-slug: renamite
      system-deps-linux: libasound2-dev libudev-dev pkg-config libx11-dev libxcb1-dev libxi-dev libxinerama-dev libxrandr-dev libxcursor-dev libfontconfig-dev libwayland-dev libxkbcommon-dev